<?php

/**
 * @file
 * Restrict access to certain nodes based on user roles
 */

/**
 * Implements hook_node_access().
 */
function roles_access_node_access($node, $op, $account) {
	$nodes = array(216, 217);
	$restricted_node = in_array($node->nid, $nodes);

	global $user;
	$allowed_user = array_intersect(
		array('Administrator', 'Redakteur'),
		array_values($user->roles));

	if ($restricted_node && !$allowed_user) {
		return NODE_ACCESS_DENY;
	}
	else {
		return NODE_ACCESS_ALLOW;
	}

	return NODE_ACCESS_IGNORE;
}